blueprint:
  name: ZHA - Tuya Smart Knob - Multi-Device (Original Logic Restored)
  description: >-
    v8 - HYBRID VERSION.
    
    Combines:
    1. Multi-Device Selection (Double Press)
    2. ORIGINAL Rotation Logic (Calculated values + Repeat loops)
    
    REQUIREMENTS:
    1. A 'Text' helper (input_text).
    2. A list of Light entities.

  domain: automation

  input:
    remote:
      name: Tuya Smart Knob
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_gwkzibhs
          model: TS004F
    
    light:
      name: Lights to Control
      description: Select the list of lights to cycle through.
      selector:
        entity:
          domain: light
          multiple: true
          
    controller_helper:
      name: Controller Memory (Input Text)
      description: The helper that stores which light is currently active.
      selector:
        entity:
          domain: input_text

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      # --- INPUTS ---
      target_lights: !input light
      helper_entity: !input controller_helper

      # --- ZHA DATA ---
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      args: "{{ trigger.event.data.args }}"
      direction: "{% if trigger.event.data.args[0] == 0 %} 0 {% elif trigger.event.data.args[0] == 1 %} 1 {% elif trigger.event.data.args[0] == 3 %} 3 {% endif %}"
      value: "{% if trigger.event.data.args[1] %} {{ trigger.event.data.args[1] / 2 }} {% endif %}"
      speed: "{% if trigger.event.data.args[2] == 1 %} 0.5 {% else %} 0 {% endif %}"
      
      # --- DETERMINE CURRENT LIGHT ---
      stored_state: "{{ states(helper_entity) | trim }}"
      current_light: >
        {% if stored_state in target_lights %}
          {{ stored_state }}
        {% else %}
          {{ target_lights[0] }}
        {% endif %}

  - choose:
      # ====================================================
      # 1. CHANGE LIGHT (Double Press)
      # ====================================================
      - conditions:
          - "{{ command == 'remote_button_double_press' }}"
        sequence:
          - variables:
              current_idx: >
                {% if current_light in target_lights %}
                  {{ target_lights.index(current_light) }}
                {% else %}
                  -1
                {% endif %}
              next_idx: "{{ (current_idx + 1) % (target_lights | length) }}"
              next_light: "{{ target_lights[next_idx] }}"
          
          # Update Helper
          - service: input_text.set_value
            target:
              entity_id: !input controller_helper
            data:
              value: "{{ next_light }}"

      # ====================================================
      # 2. ROTATE RIGHT (Brighten) - Original Logic
      # ====================================================
      - conditions:
          - "{{ command == 'left' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ current_light }}"

      # ====================================================
      # 3. ROTATE LEFT (Dim) - Original Logic
      # ====================================================
      - conditions:
          - "{{ command == 'right' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ current_light }}"

      # ====================================================
      # 4. TOGGLE (Short Press)
      # ====================================================
      - conditions:
          - "{{ command == 'toggle' or command == 'remote_button_short_press' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ current_light }}"
