blueprint:
  name: ZHA - Tuya - TS004F Smart Knob - Fixed Target
  description: >-
    v9 - TARGET FIX.
    
    Fixed 'Message Malformed' error by moving entity_id out of the target block.
    
    Controls multiple lights with one Tuya TS004F Rotary Knob.
    - Double Press: Switch Light.
    - Rotate: Dim Current Light.
    - Short Press: Toggle Current Light.

  domain: automation

  input:
    mode:
      name: Automation Mode
      default: restart
      selector:
        select:
          mode: dropdown
          options:
            - single
            - restart
            - queued
            - parallel
    max:
      name: Automation Max Executions
      default: 10
      selector:
        number:
          mode: box
          min: 1
          max: 100
    remote:
      name: Tuya - TS004F Smart Knob
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_gwkzibhs
          model: TS004F
    light:
      name: Lights to Control
      description: Select the list of lights to cycle through.
      selector:
        entity:
          domain: light
          multiple: true
    controller_helper:
      name: Controller Memory (Input Text)
      selector:
        entity:
          domain: input_text
    toggle:
      name: Toggle (Command/Dimmer mode)
      selector:
        action:
      default: []
    press_long:
      name: Long Press (Event/Scene mode)
      selector:
        action:
      default: []
    rotate_left:
      name: Rotate Left (Event/Scene mode)
      selector:
        action:
      default: []
    rotate_right:
      name: Rotate Right (Event/Scene mode)
      selector:
        action:
      default: []

mode: !input mode
max: !input max
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      target_lights: !input light
      helper_entity: !input controller_helper
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      args: "{{ trigger.event.data.args }}"
      
      direction: >
        {% if trigger.event.data.args[0] is defined %}
          {% if trigger.event.data.args[0] == 0 %} 0
          {% elif trigger.event.data.args[0] == 1 %} 1
          {% elif trigger.event.data.args[0] == 3 %} 3
          {% endif %}
        {% else %} 0 {% endif %}

      value: >
        {% if trigger.event.data.args[1] is defined %}
          {{ trigger.event.data.args[1] / 2 }}
        {% else %} 10 {% endif %}

      speed: >
        {% if trigger.event.data.args[2] is defined and trigger.event.data.args[2] == 1 %} 0.5 
        {% else %} 0 {% endif %}

      stored_state: "{{ states(helper_entity) | trim }}"
      current_light: >
        {% if stored_state in target_lights %}
          {{ stored_state }}
        {% else %}
          {{ target_lights[0] }}
        {% endif %}

  - choose:
      # -------------------------------------------------------------------
      # Command Mode: Toggle
      # -------------------------------------------------------------------
      - conditions:
          - "{{ command == 'toggle' }}"
          - "{{ cluster_id == 6 }}"
          - "{{ endpoint_id == 1 }}"
        sequence: !input toggle

      # -------------------------------------------------------------------
      # Command Mode: Dimming (Rotate Right/Up)
      # -------------------------------------------------------------------
      - conditions:
          - "{{ command == 'step' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ direction == 0 }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ repeat.index < 2 }}"
              sequence:
                - service: light.turn_on
                  entity_id: "{{ current_light }}"
                  data:
                    brightness_step_pct: "{{ value }}"
                    transition: "{{ speed }}"

      # -------------------------------------------------------------------
      # Command Mode: Dimming (Rotate Left/Down)
      # -------------------------------------------------------------------
      - conditions:
          - "{{ command == 'step' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ direction == 1 }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ repeat.index < 2 }}"
              sequence:
                - service: light.turn_on
                  entity_id: "{{ current_light }}"
                  data:
                    brightness_step_pct: "{{ - value }}"
                    transition: "{{ speed }}"

      # -------------------------------------------------------------------
      # Command Mode: Color Temp (Warm)
      # -------------------------------------------------------------------
      - conditions:
          - "{{ command == 'step_color_temp' }}"
          - "{{ cluster_id == 768 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ direction == 1 }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ repeat.index < 2 }}"
              sequence:
                - service: light.turn_on
                  entity_id: "{{ current_light }}"
                  data:
                    color_temp: "{{ (state_attr(current_light, 'color_temp') or 300) + value }}"
                    transition: "{{ speed }}"

      # -------------------------------------------------------------------
      # Command Mode: Color Temp (Cool)
      # -------------------------------------------------------------------
      - conditions:
          - "{{ command == 'step_color_temp' }}"
          - "{{ cluster_id == 768 }}"
          - "{{ endpoint_id == 1 }}"
          - "{{ direction == 3 }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ repeat.index < 2 }}"
              sequence:
                - service: light.turn_on
                  entity_id: "{{ current_light }}"
                  data:
                    color_temp: "{{ (state_attr(current_light, 'color_temp') or 300) - value }}"
                    transition: "{{ speed }}"

      # -------------------------------------------------------------------
      # Command Mode: Color Hue
