blueprint:
  name: ZHA - Tuya Smart Knob - Multi-Device (v5 - Type Fix)
  description: >-
    FIXED: Forces number conversion for rotation data.
    
    Controls multiple lights with one Tuya TS004F Rotary Knob.
    
    - Double Press: Switch to the next light in the list.
    - Rotate: Dims the CURRENTLY selected light (regardless of knob mode).
    - Short Press: Toggle the CURRENTLY selected light.
    
    REQUIREMENTS:
    1. A 'Text' helper (input_text).
    2. A list of Light entities.

  domain: automation

  input:
    remote:
      name: Tuya Smart Knob
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_gwkzibhs
          model: TS004F
    
    light:
      name: Lights to Control
      description: Select the list of lights to cycle through.
      selector:
        entity:
          domain: light
          multiple: true
          
    controller_helper:
      name: Controller Memory (Input Text)
      description: The helper that stores which light is currently active.
      selector:
        entity:
          domain: input_text

    step_size:
      name: Rotation Step Size
      description: Percentage to change brightness per click.
      default: 15
      selector:
        number:
          min: 1
          max: 100
          mode: slider

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      # --- LOAD INPUTS ---
      target_lights: !input light
      helper_entity: !input controller_helper
      step: !input step_size
      
      # --- ZHA EVENT DATA ---
      command: "{{ trigger.event.data.command }}"
      args: "{{ trigger.event.data.args | default([]) }}"
      
      # --- DETERMINE CURRENT LIGHT ---
      stored_state: "{{ states(helper_entity) | trim }}"
      
      current_light: >
        {% if stored_state in target_lights %}
          {{ stored_state }}
        {% else %}
          {{ target_lights[0] }}
        {% endif %}

  - choose:
      # ====================================================
      # 1. CHANGE LIGHT (Double Press)
      # ====================================================
      - conditions:
          - "{{ command == 'remote_button_double_press' }}"
        sequence:
          - variables:
              current_idx: >
                {% if current_light in target_lights %}
                  {{ target_lights.index(current_light) }}
                {% else %}
                  -1
                {% endif %}
              next_idx: "{{ (current_idx + 1) % (target_lights | length) }}"
              next_light: "{{ target_lights[next_idx] }}"
          
          # Update Helper
          - service: input_text.set_value
            target:
              entity_id: !input controller_helper
            data:
              value: "{{ next_light }}"
          
          # Flash New Light
          - service: light.turn_on
            target:
              entity_id: "{{ next_light }}"
            data:
              flash: short
              brightness_pct: 100

      # ====================================================
      # 2. ROTATE RIGHT (Brighten)
      # ====================================================
      # Checks 'step' (args[0]=0), 'right', or 'move_hue'
      - conditions:
          - >
            {{ 
               (command == 'step' and args | length > 0 and args[0] | int == 0) 
               or 
               (command == 'right')
               or
               (command == 'step_color_temp' and args | length > 0 and args[0] | int == 1)
            }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ current_light }}"
            data:
              brightness_step_pct: "{{ step | int }}"
              transition: 0.1

      # ====================================================
      # 3. ROTATE LEFT (Dim)
      # ====================================================
      # Checks 'step' (args[0]=1), 'left', or 'move_hue'
      - conditions:
          - >
            {{ 
               (command == 'step' and args | length > 0 and args[0] | int == 1) 
               or 
               (command == 'left')
               or
               (command == 'step_color_temp' and args | length > 0 and args[0] | int == 3)
            }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ current_light }}"
            data:
              brightness_step_pct: "{{ (step | int) * -1 }}"
              transition: 0.1

      # ====================================================
      # 4. TOGGLE (Short Press)
      # ====================================================
      - conditions:
          - "{{ command == 'toggle' or command == 'remote_button_short_press' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ current_light }}"
