blueprint:
  name: ZHA - Tuya Smart Knob - Multi-Device (Log Fixed)
  description: >-
    v7 - LOG BASED FIX.
    
    Uses 'step_mode' from ZHA parameters to detect rotation direction.
    
    Controls multiple lights with one Tuya TS004F Rotary Knob.
    - Double Press: Switch to the next light.
    - Rotate: Dim the CURRENTLY selected light.
    - Short Press: Toggle the CURRENTLY selected light.
    
    REQUIREMENTS:
    1. A 'Text' helper (input_text).
    2. A list of Light entities.

  domain: automation

  input:
    remote:
      name: Tuya Smart Knob
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_gwkzibhs
          model: TS004F
    
    light:
      name: Lights to Control
      description: Select the list of lights to cycle through.
      selector:
        entity:
          domain: light
          multiple: true
          
    controller_helper:
      name: Controller Memory (Input Text)
      description: The helper that stores which light is currently active.
      selector:
        entity:
          domain: input_text

    step_size:
      name: Rotation Step Size
      description: Percentage to change brightness per click.
      default: 15
      selector:
        number:
          min: 1
          max: 100
          mode: slider

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      # --- INPUTS ---
      target_lights: !input light
      helper_entity: !input controller_helper
      step: !input step_size

      args: "{{ trigger.event.data.args }}"
      direction: "{% if trigger.event.data.args[0] == 0 %} 0 {% elif trigger.event.data.args[0] == 1 %} 1 {% elif trigger.event.data.args[0] == 3 %} 3 {% endif %}"
      value: "{% if trigger.event.data.args[1] %} {{ trigger.event.data.args[1] / 2 }} {% endif %}"
      speed: "{% if trigger.event.data.args[2] == 1 %} 0.5 {% else %} 0 {% endif %}"
      command: "{{ trigger.event.data.command }}"
      
      # --- EVENT DATA ---vcfgggg nbcccccccccccccccccccccccc
      params: "{{ trigger.event.data.params | default({}) }}"
      
      # --- DETERMINE CURRENT LIGHT ---
      stored_state: "{{ states(helper_entity) | trim }}"
      current_light: >
        {% if stored_state in target_lights %}
          {{ stored_state }}
        {% else %}
          {{ target_lights[0] }}
        {% endif %}

  - choose:
      # -------------------------------------------------------------------
      # ACTION: CHANGE DEVICE (Double Press)
      # -------------------------------------------------------------------
      - conditions:
          - "{{ command == 'remote_button_double_press' }}"
        sequence:
          # Calculate the next light in the list
          - variables:
              next_light: >
                {% set i = lights_list.index(current_light) %}
                {% set next_i = (i + 1) % (lights_list | length) %}
                {{ lights_list[next_i] }}
          # Update the helper
          - service: input_text.set_value
            target:
              entity_id: !input controller_helper
            data:
              value: "{{ next_light }}"
          # Visual Feedback: Flash the new light so user knows it changed
          - service: light.turn_on
            target:
              entity_id: "{{ next_light }}"
            data:
              flash: short
        


      # ====================================================
      # 2. ROTATE RIGHT (Brighten)
      # ====================================================
      # Checks 'step' command AND 'step_mode: 0' (from your log)
      - conditions:
          - "{{ command == 'step' }}"
          - "{{ direction == 0 }}"
        sequence:
        - repeat:
            while:
              - condition: template
                value_template: "{{ repeat.index < 2 }}"
            sequence:
              - service_template: light.turn_on
                target:
                  entity_id: "{{ current_light }}"
                data_template:
                  brightness_step_pct: "{{ value }}"
                  transition: "{{ speed }}"


        - conditions:
            - "{{ command == 'step' }}"
            - "{{ direction == 1 }}"
          sequence:
            - repeat:
                while:
                  - condition: template
                    value_template: "{{ repeat.index < 2 }}"
                sequence:
                  - service_template: light.turn_on
                    target:
                      entity_id: "{{ current_light }}"
                    data_template:
                      brightness_step_pct: "{{ - value }}"
                      transition: "{{ speed }}"




      # ====================================================
      # 4. TOGGLE (Short Press)
      # ====================================================
      - conditions:
          - "{{ command == 'toggle' or command == 'remote_button_short_press' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ current_light }}"
