blueprint:

  name: ZHA - Tuya - TS004F Smart Knob - Custom Actions

  description: >-
    This automation adds triggers for all actions of the Tuya TS004F rotary knob remote.
    It can be used in both Command/Dimmer mode and Event/Scene mode. Both modes have their own actions.
    In Command/Dimmer mode, the configuration is mostly internal except for button press.
    In Event/Scene mode, you can select your own actions.
    To switch between modes, you can quickly press the button 3 times.
    Sold on AliExpress by brands like Moes, Girier, etc.

  domain: automation

  input:
    mode:
      name: Automation Mode
      description: "https://www.home-assistant.io/docs/automation/modes/"
      default: restart
      selector:
        select:
          mode: dropdown
          options:
            - single
            - restart
            - queued
            - parallel
    max:
      name: Automation Max Executions
      description: The maximum number of executions that can be run and queued at one time.
      default: 10
      selector:
        number:
          mode: box
          min: 1
          max: 100
    remote:
      name: Tuya - TS004F Smart Knob
      description: Select the remote you want to use.
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_gwkzibhs
          model: TS004F
    light:
      name: Light (Command/Dimmer mode)
      selector:
        target:
          entity:
            domain: light
    lights:
      name: Lights to Control
      description: Select the list of lights to cycle through.
      selector:
        entity:
          domain: light
          multiple: true
    controller_helper:
      name: Controller Memory (Input Text)
      selector:
        entity:
          domain: input_text
    toggle:
      name: Toggle (Command/Dimmer mode)
      selector:
        action:
      default: []
    press_short:
      name: Short Press (Event/Scene mode)
      selector:
        action:
      default: []
    press_double:
      name: Double Press (Event/Scene mode)
      selector:
        action:
      default: []
    press_long:
      name: Long Press (Event/Scene mode)
      selector:
        action:
      default: []
    rotate_left:
      name: Rotate Left (Event/Scene mode)
      selector:
        action:
      default: []
    rotate_right:
      name: Rotate Right (Event/Scene mode)
      selector:
        action:
      default: []

mode: !input mode
max: !input max
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      lights: !input lights
      light: !input light
      helper_entity: !input controller_helper
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      args: "{{ trigger.event.data.args }}"
      direction: "{% if trigger.event.data.args[0] == 0 %} 0 {% elif trigger.event.data.args[0] == 1 %} 1 {% elif trigger.event.data.args[0] == 3 %} 3 {% endif %}"
      value: "{% if trigger.event.data.args[1] %} {{ trigger.event.data.args[1] / 2 }} {% endif %}"
      speed: "{% if trigger.event.data.args[2] == 1 %} 0.5 {% else %} 0 {% endif %}"
      stored_state: "{{ states(helper_entity) | trim }}"
      current_light: >
        {% if stored_state in lights %}
          {{ stored_state }}
        {% else %}
          {{ lights[0] }}
        {% endif %}

  - choose:

    # Command Mode
    - conditions:
        - "{{ command == 'toggle' }}"
        - "{{ cluster_id == 6 }}"
        - "{{ endpoint_id == 1 }}"
      sequence: !input toggle

    # Command Mode: Dimming
    - conditions:
        - "{{ command == 'step' }}"
        - "{{ cluster_id == 8 }}"
        - "{{ endpoint_id == 1 }}"
        - "{{ direction == 0 }}"
      sequence:
        - repeat:
            while:
              - condition: template
                value_template: "{{ repeat.index < 2 }}"
            sequence:
              - service_template: light.turn_on
                target: !input light
                data_template:
                  brightness_step_pct: "{{ value }}"
                  transition: "{{ speed }}"
    - conditions:
        - "{{ command == 'step' }}"
        - "{{ cluster_id == 8 }}"
        - "{{ endpoint_id == 1 }}"
        - "{{ direction == 1 }}"
      sequence:
        - repeat:
            while:
              - condition: template
                value_template: "{{ repeat.index < 2 }}"
            sequence:
              - service_template: light.turn_on
                target: !input light
                data_template:
                  brightness_step_pct: "{{ - value }}"
                  transition: "{{ speed }}"

    # Command Mode: Color Temperature
    - conditions:
        - "{{ command == 'step_color_temp' }}"
        - "{{ cluster_id == 768 }}"
        - "{{ endpoint_id == 1 }}"
        - "{{ direction == 1 }}"
      sequence:
        - repeat:
            while:
              - condition: template
                value_template: "{{ repeat.index < 2 }}"
            sequence:
              - service_template: light.turn_on
                target: !input light
                data_template:
                  color_temp: "{{ ( state_attr( light.entity_id, 'color_temp' ) or 300 ) + value }}"
                  transition: "{{ speed }}"
    - conditions:
        - "{{ command == 'step_color_temp' }}"
        - "{{ cluster_id == 768 }}"
        - "{{ endpoint_id == 1 }}"
        - "{{ direction == 3 }}"
      sequence:
        - repeat:
            while:
              - condition: template
                value_template: "{{ repeat.index < 2 }}"
            sequence:
              - service_template: light.turn_on
                target: !input light
                data_template:
                  color_temp: "{{ ( state_attr( light.entity_id, 'color_temp' ) or 300 ) - value }}"
                  transition: "{{ speed }}"

    # Command Mode: Color Hue
    - conditions:
        - "{{ command == 'move_hue' }}"
        - "{{ cluster_id == 768 }}"
        - "{{ endpoint_id == 1 }}"
      sequence:
        - repeat:
            while:
              - condition: template
                value_template: "{{ repeat.index < 24 }}"
            sequence:
              - service_template: light.turn_on
                target: !input light
                data_template:
                  hs_color:
                    - "{{ ( value + (state_attr( light.entity_id , 'hs_color' )[0] or 0)) % 360 }}"
                    - 100
                  transition: 0.5
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 1
                  milliseconds: 0

    # Event mode: Short Press
    - conditions:
        - "{{ command == 'remote_button_short_press' }}"
      sequence:
        - service: light.toggle
          target:
            entity_id: "{{ current_light }}"

    # Event mode: Double Press
    - conditions:
        - "{{ command == 'remote_button_double_press' }}"
      sequence:
        - variables:
            current_idx: >
              {% if current_light in lights %}
                {{ lights.index(current_light) }}
              {% else %}
                -1
              {% endif %}
            next_idx: "{{ (current_idx + 1) % (lights | length) }}"
            next_light: "{{ lights[next_idx] }}"
        - service: input_text.set_value
          target:
            entity_id: !input controller_helper
          data:
            value: "{{ next_light }}"

    # Event mode: Long Press
    - conditions:
        - "{{ command == 'remote_button_long_press' }}"
      sequence: !input press_long

    # Event mode: Rotate Left
    - conditions:
        - "{{ command == 'left' }}"
      sequence: !input rotate_left

    # Event mode: Rotate Right
    - conditions:
        - "{{ command == 'right' }}"
      sequence: !input rotate_right
