blueprint:
  name: ZHA - Tuya Smart Knob - Multi-Device (Fixed)
  description: >-
    FIXED VERSION.
    
    Controls multiple lights with one Tuya TS004F Rotary Knob.
    
    - Double Press: Switch to the next light in the list.
    - Rotate: Dim the CURRENTLY selected light.
    - Short Press: Toggle the CURRENTLY selected light.
    
    REQUIREMENTS:
    1. A 'Text' helper (input_text) to store the active light.
    2. A list of Light entities.

  domain: automation

  input:
    remote:
      name: Tuya Smart Knob
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_gwkzibhs
          model: TS004F
    
    light:
      name: Lights to Control
      description: Select the Light Entities to cycle through.
      selector:
        entity:
          domain: light
          multiple: true
          
    controller_helper:
      name: Current Light Helper
      description: Select the input_text helper you created.
      selector:
        entity:
          domain: input_text

    sensitivity:
      name: Rotation Sensitivity
      description: Percentage to change brightness per rotation step.
      default: 10
      selector:
        number:
          min: 1
          max: 100
          mode: slider

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      # --- LOAD INPUTS ---
      lights_list: !input light
      helper_entity: !input controller_helper
      sensitivity: !input sensitivity
      
      # --- PARSE EVENT DATA ---
      command: "{{ trigger.event.data.command }}"
      args: "{{ trigger.event.data.args | default([]) }}"
      
      # --- DETERMINE CURRENT LIGHT ---
      # 1. Read the helper state.
      # 2. Trim whitespace.
      # 3. If valid and in our list, use it. Otherwise reset to first light.
      stored_entity: "{{ states(helper_entity) | trim }}"
      current_light: >
        {% if stored_entity in lights_list %}
          {{ stored_entity }}
        {% else %}
          {{ lights_list[0] }}
        {% endif %}

  - choose:
      # ====================================================
      # 1. CHANGE LIGHT (Double Press)
      # ====================================================
      - conditions:
          - "{{ command == 'remote_button_double_press' }}"
        sequence:
          - variables:
              next_light: >
                {% set i = lights_list.index(current_light) %}
                {% set next_i = (i + 1) % (lights_list | length) %}
                {{ lights_list[next_i] }}
          
          # Save to Helper
          - service: input_text.set_value
            target:
              entity_id: !input controller_helper
            data:
              value: "{{ next_light }}"
          
          # Visual Confirm: Flash the NEW light
          - service: light.turn_on
            target:
              entity_id: "{{ next_light }}"
            data:
              flash: short

      # ====================================================
      # 2. TOGGLE (Short Press)
      # ====================================================
      # Covers both 'toggle' (Command Mode) and 'short_press' (Event Mode)
      - conditions:
          - "{{ command == 'toggle' or command == 'remote_button_short_press' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ current_light }}"

      # ====================================================
      # 3. ROTATE RIGHT (Dim Up)
      # ====================================================
      # Case A: Command Mode (Step command, direction 0)
      - conditions:
          - "{{ command == 'step' }}"
          - "{{ args | length > 0 }}"
          - "{{ args[0] == 0 }}" 
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ current_light }}"
            data:
              brightness_step_pct: "{{ sensitivity }}"
              transition: 0.1

      # Case B: Scene Mode (Right command)
      - conditions:
          - "{{ command == 'right' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ current_light }}"
            data:
              brightness_step_pct: "{{ sensitivity }}"
              transition: 0.1

      # ====================================================
      # 4. ROTATE LEFT (Dim Down)
      # ====================================================
      # Case A: Command Mode (Step command, direction 1)
      - conditions:
          - "{{ command == 'step' }}"
          - "{{ args | length > 0 }}"
          - "{{ args[0] == 1 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ current_light }}"
            data:
              brightness_step_pct: "-{{ sensitivity }}"
              transition: 0.1

      # Case B: Scene Mode (Left command)
      - conditions:
          - "{{ command == 'left' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ current_light }}"
            data:
              brightness_step_pct: "-{{ sensitivity }}"
              transition: 0.1

      # ====================================================
      # 5. LONG PRESS (Optional reset or color cycle)
      # ====================================================
      - conditions:
          - "{{ command == 'remote_button_long_press' }}"
        sequence:
           # Reset brightness to 50% on long press (optional default behavior)
          - service: light.turn_on
            target:
              entity_id: "{{ current_light }}"
            data:
              brightness_pct: 50
