blueprint:
  name: ZHA - Tuya Smart Knob - Multi-Device (Robust)
  description: >-
    v3.0 - ROBUST VERSION.
    
    - Fixes rotation issues by simplifying Zigbee command parsing.
    - Fixes list looping (returns to start correctly).
    
    REQUIREMENTS:
    1. Create an 'input_text' helper (Settings > Devices > Helpers > Create > Text).
    2. Select that helper below.
    3. Select your list of lights.

  domain: automation

  input:
    remote:
      name: Tuya Smart Knob
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_gwkzibhs
          model: TS004F
    
    light:
      name: Lights to Control
      description: Select the list of lights to cycle through.
      selector:
        entity:
          domain: light
          multiple: true
          
    controller_helper:
      name: Controller Memory (Input Text)
      description: The helper that stores which light is currently active.
      selector:
        entity:
          domain: input_text

    step_size:
      name: Rotation Step Size
      description: How much to change brightness per click (percentage).
      default: 15
      selector:
        number:
          min: 1
          max: 100
          mode: slider

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      # --- LOAD INPUTS ---
      target_lights: !input light
      helper_entity: !input controller_helper
      step: !input step_size

      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      direction: "{% if trigger.event.data.args[0] == 0 %} 0 {% elif trigger.event.data.args[0] == 1 %} 1 {% elif trigger.event.data.args[0] == 3 %} 3 {% endif %}"
      value: "{% if trigger.event.data.args[1] %} {{ trigger.event.data.args[1] / 2 }} {% endif %}"
      speed: "{% if trigger.event.data.args[2] == 1 %} 0.5 {% else %} 0 {% endif %}"
      
      # --- ZHA EVENT DATA ---
      command: "{{ trigger.event.data.command }}"
      args: "{{ trigger.event.data.args }}"
      
      # --- DETERMINE CURRENT LIGHT ---
      # Get the text from the helper
      stored_state: "{{ states(helper_entity) | trim }}"
      
      # Logic: If the stored light is in our list, use it. 
      # If not (or if empty), DEFAULT to the first light in the list.
      current_light: >
        {% if stored_state in target_lights %}
          {{ stored_state }}
        {% else %}
          {{ target_lights[0] }}
        {% endif %}

  - choose:
      # ====================================================
      # 1. CHANGE LIGHT (Double Press)
      # ====================================================
      - conditions:
          - "{{ command == 'remote_button_double_press' }}"
        sequence:
          - variables:
              # Find current index. If not found, default to -1
              current_idx: >
                {% if current_light in target_lights %}
                  {{ target_lights.index(current_light) }}
                {% else %}
                  -1
                {% endif %}
              
              # Calculate next index. (idx + 1) % total gives us the loop back to 0
              next_idx: "{{ (current_idx + 1) % (target_lights | length) }}"
              next_light: "{{ target_lights[next_idx] }}"
          
          # 1. Update Helper
          - service: input_text.set_value
            target:
              entity_id: !input controller_helper
            data:
              value: "{{ next_light }}"
          
          # 2. Flash the NEW light so you know it changed
          - service: light.turn_on
            target:
              entity_id: "{{ next_light }}"
            data:
              flash: short
              brightness_pct: 100 # Ensure it's visible

      # ====================================================
      # 2. ROTATION: CLOCKWISE (Brighten)
      # ====================================================
      # Matches 'step' with arg 0 OR 'right' (scene mode)
      - conditions:
        - "{{ command == 'right' }}"
        sequence:
              - service_template: light.turn_on
                target:
                  entity_id: !input controller_helper
                data_template:
                  brightness_step_pct: "{{ value }}"
                  transition: "{{ speed }}"

      # ====================================================
      # 3. ROTATION: COUNTER-CLOCKWISE (Dim)
      # ====================================================
      # Matches 'step' with arg 1 OR 'left' (scene mode)
      - conditions:
        - "{{ command == 'left' }}"
        sequence:
              - service_template: light.turn_on
                target:
                  entity_id: !input controller_helper
                data_template:
                  brightness_step_pct: "{{ - value }}"
                  transition: "{{ speed }}"

      # ====================================================
      # 4. TOGGLE (Short Press)
      # ====================================================
      - conditions:
          - "{{ command == 'toggle' or command == 'remote_button_short_press' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ current_light }}"
