blueprint:
  name: ZHA - Tuya Smart Knob - Multi-Device (Original Logic Restored)
  description: >-
    v8 - HYBRID VERSION.
    
    Combines:
    1. Multi-Device Selection (Double Press)
    2. ORIGINAL Rotation Logic (Calculated values + Repeat loops)
    
    REQUIREMENTS:
    1. A 'Text' helper (input_text).
    2. A list of Light entities.

  domain: automation

  input:
    remote:
      name: Tuya Smart Knob
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_gwkzibhs
          model: TS004F
    
    light:
      name: Lights to Control
      description: Select the list of lights to cycle through.
      selector:
        entity:
          domain: light
          multiple: true
          
    controller_helper:
      name: Controller Memory (Input Text)
      description: The helper that stores which light is currently active.
      selector:
        entity:
          domain: input_text

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      # --- INPUTS ---
      target_lights: !input light
      helper_entity: !input controller_helper

      # --- ZHA DATA ---
      command: "{{ trigger.event.data.command }}"
      args: "{{ trigger.event.data.args | default([]) }}"
      
      # --- ORIGINAL CALCULATIONS ---
      # Direction: 0 (Right), 1 (Left)
      direction: >
        {% if args[0] is defined %}
          {% if args[0] == 0 %} 0
          {% elif args[0] == 1 %} 1
          {% elif args[0] == 3 %} 3
          {% endif %}
        {% else %} 0
        {% endif %}
      
      # Value: Step size derived from args[1]
      value: >
        {% if args[1] is defined %}
          {{ args[1] / 2 }}
        {% else %}
          10
        {% endif %}
      
      # Speed: Transition time derived from args[2]
      speed: >
        {% if args[2] is defined and args[2] == 1 %}
          0.5
        {% else %}
          0
        {% endif %}
      
      # --- DETERMINE CURRENT LIGHT ---
      stored_state: "{{ states(helper_entity) | trim }}"
      current_light: >
        {% if stored_state in target_lights %}
          {{ stored_state }}
        {% else %}
          {{ target_lights[0] }}
        {% endif %}

  - choose:
      # ====================================================
      # 1. CHANGE LIGHT (Double Press)
      # ====================================================
      - conditions:
          - "{{ command == 'remote_button_double_press' }}"
        sequence:
          - variables:
              current_idx: >
                {% if current_light in target_lights %}
                  {{ target_lights.index(current_light) }}
                {% else %}
                  -1
                {% endif %}
              next_idx: "{{ (current_idx + 1) % (target_lights | length) }}"
              next_light: "{{ target_lights[next_idx] }}"
          
          # Update Helper
          - service: input_text.set_value
            target:
              entity_id: !input controller_helper
            data:
              value: "{{ next_light }}"
          
          # Visual Feedback
          - service: light.turn_on
            target:
              entity_id: "{{ next_light }}"
            data:
              flash: short
              brightness_pct: 100 # Ensure visible

      # ====================================================
      # 2. ROTATE RIGHT (Brighten) - Original Logic
      # ====================================================
      - conditions:
          - "{{ command == 'left' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ repeat.index < 2 }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ current_light }}"
                  data:
                    brightness_step_pct: "{{ value }}"
                    transition: "{{ speed }}"

      # ====================================================
      # 3. ROTATE LEFT (Dim) - Original Logic
      # ====================================================
      - conditions:
          - "{{ command == 'right' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ repeat.index < 2 }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ current_light }}"
                  data:
                    brightness_step_pct: "{{ - value }}"
                    transition: "{{ speed }}"

      # ====================================================
      # 4. TOGGLE (Short Press)
      # ====================================================
      - conditions:
          - "{{ command == 'toggle' or command == 'remote_button_short_press' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ current_light }}"
